# -*- coding: utf-8 -*-
"""Prueba Técnica — Data Engineer Intern.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VKUBwPElwSPr4QK_9rUOPkjW1YL0jMi7

# Fase 1 - Exploración de datos
Lo primero que se realizará es la exploración de los datos con ayuda de Colab para el pr-análisis del estado de los datos
"""

import pandas as pd

df = pd.read_csv("/content/healthcare_dataset.csv")
df

"""Revisamos las caracteristicas de los valores asi como el total de registros     """

df.info()

"""## Valores  nulos, blancos

Lo primero que revisamos es:


*  **Valores Nulos**: aunque la funcion .info() nos menciona que no, podemos revisarlo por nuestra cuenta para una doble verificación
*  **Valores blancos**: revisar si los datos tienen valores completos pero que pueden ser "basura" ya que solo esta completado para no tener nulos
*   **Valores duplicados**: revisar si existen valores duplicados entre la combinacion de todas las variables
"""

# Conteo de valores nulos (NaN)
null_count = df.isnull().sum()

# Conteo de valores en blanco (strings vacíos o solo espacios)
blank_count = (df.astype(str).apply(lambda x: x.str.strip()) == "").sum()

# 3. Porcentaje de datos faltantes
missing_percent = (null_count / len(df)) * 100

df_diagnosis = pd.DataFrame({
    'Tipo de Dato': df.dtypes,
    'Nulos (NaN)': null_count,
    'Blancos (" ")': blank_count,
    '% Faltante Total': missing_percent
})

print("--- Diagnóstico de Calidad de Datos ---")
print(df_diagnosis)

# Filas duplicadas
print(f"\nTotal de filas duplicadas: {df.duplicated().sum()}")

"""## Valores duplicados

Observamos que no se tiene valores tanto nulos como ben blanco pero si se tiene valores duplicados por lo que revisaremos si esos valores son en realidad duplciados y de que tipo son
"""

# Filtramos el dataframe para mostrar SOLO las filas que tienen duplicados
df_repetidos = df[df.duplicated(keep=False)]

# Ordenamos por todas las columnas para que las filas idénticas aparezcan juntas
df_repetidos_ordenados = df_repetidos.sort_values(by=list(df.columns))

# Mostramos los primeros 10 registros de este grupo de duplicados
print("--- Visualización de registros duplicados (Filas idénticas juntas) ---")
if not df_repetidos_ordenados.empty:
    print(df_repetidos_ordenados.head(10))
else:
    print("No se encontraron filas duplicadas exactas en el dataset.")

"""Con esto nos damos cuenta de que son por tal cual por valores duplicadosen el registro, asi que lo que sigue ahora es saber si son solo valores que se insertaron 2 veces o mas, por lo que se ve cuanto es el conteo de duplicados por cada valor, teniendo el resumen para saber las veces que se repite"""

# Contamos cuántas veces aparece cada combinación de filas
frecuencia_duplicados = df.groupby(df.columns.tolist()).size().reset_index(name='cantidad')

# Filtramos para quedarnos solo con los que aparecen más de 1 vez
solo_duplicados = frecuencia_duplicados[frecuencia_duplicados['cantidad'] > 1]

# Ordenamos de mayor a menor para ver los "peores" casos primero
solo_duplicados = solo_duplicados.sort_values(by='cantidad', ascending=False)

print("--- Top 10 de registros más repetidos ---")
print(solo_duplicados.head(10))

# Resumen de las repeticiones
print("\n--- Distribución de las repeticiones ---")
print(solo_duplicados['cantidad'].value_counts().sort_index().rename_axis('Veces que se repite').reset_index(name='Cantidad de grupos'))

"""Al saber que solo se tiene 2 valores duplicadosen un total de 534, lo que se presencio al inicio, son filas duplicadas 2 veces por lo que se arregla eliminando la duplicada

Algo que resaltar en esta parte es que la varibale name tiene datos con letras mayusculas y minusculas mezcladas, por lo que en la limpieza de los datos se consideraria dejar solo la primera en mayuscula y las demas en minuscula.

## Valores unicos
"""

print("--- Valores únicos por columna ---")
print(df.nunique())

"""Revisamos los valores unicos en cada una de las columnas, para ver si hay datos sucios, ya que claro mencionamos que no hay nulos y blancos pero no necesariamente significa que sea valida esa data"""

print("--- Exploración de Valores Únicos (Orden Ascendente) ---\n")

for columna in df.columns:
    # Obtener valores únicos, quitar nulos y convertir a lista de Python pura
    unique_values = df[columna].unique().tolist()
    total_unicos = len(unique_values)

    # Ordenar de forma ascendente estándar
    valores_ordenados = sorted(unique_values)

    print(f"Columna: '{columna}' | Tipo: {df[columna].dtype} | Únicos: {total_unicos}")

    # Mostrar la muestra de los 20 primeros
    if total_unicos > 20:
        print(f"Muestra de los 20 primeros:")
        print(valores_ordenados[:20])
    else:
        print(f"Todos los valores:")
        print(valores_ordenados)

    print("-" * 50)

"""## Valores Atipicos

Revisamos los valores apiticos para cada columna, para lo que ellos nos resulta mas facil observar estos valore sen histogramas, para ver la dispersion de los datos

Primero transformamos los datos categoricos a valores numericos para que sea posible realizar las graficas
"""

# Identificar columnas categóricas (las que son tipo 'object')
categoricas = df.select_dtypes(include=['object']).columns

# Creamos un nuevo DataFrame para no arruinar el original
df_numerico = df.copy()

for col in categoricas:
    df_numerico[col] = df_numerico[col].astype('category').cat.codes

print(df_numerico.head())

import matplotlib.pyplot as plt

# Primero normalizamos nombres para evitar el KeyError
df_numerico.columns = df_numerico.columns.str.strip().str.lower().str.replace(' ', '_')

# Dibujamos histogramas de todas las columnas numéricas
df_numerico.hist(figsize=(15, 10), bins=30, edgecolor='black')
plt.suptitle('Distribución de Variables Numéricas (Campanas)', fontsize=16)
plt.tight_layout()
plt.show()

"""Observamos que no existen valores atipicos representativos o casi no estan presentes,

## Validaciones de fecha

Ahora validamos las fechas de admision con las de alta, asi para identificar si hay valores que no sean del tipo, lo admiti el dia jueves 10 y lo di de alta el dia martes 08, como ejemplo, por lo que una nueva variable "days_of_stay" vamos a crear
"""

# Aseguramos que las columnas sean tipo fecha (datetime)
df['date_of_admission'] = pd.to_datetime(df['date_of_admission'])
df['discharge_date'] = pd.to_datetime(df['discharge_date'])

# Calculamos la diferencia y extraemos solo el número de días
df['days_of_stay'] = (df['discharge_date'] - df['date_of_admission']).dt.days

# Revisamos los primeros resultados
print(df[['date_of_admission', 'discharge_date', 'days_of_stay']].head())

df.describe()

print(sorted(df["days_of_stay"].unique().tolist()))

"""# Fase 2 - Limpieza y Transformacion

Lo primero que haremos es volver a cargar el dataset y guardar una copia en otro dataframe para ir realizando la limpieza que antes mencionamos
"""

import pandas as pd

# Cargar el dataset original
df_original = pd.read_csv('healthcare_dataset.csv')

# Crear la copia para limpieza
df_limpio = df_original.copy()

# Normalización de cabeceras (Snake Case)
# Justificación: Evita errores de sintaxis y facilita el acceso a columnas en Python.
df_limpio.columns = df_limpio.columns.str.strip().str.lower().str.replace(' ', '_')

"""## Eliminar duplicados

Eliminamos los duplicados que encontramos anteriormente, mostramos cuantas columnas nos queda y cuantas registros nos quedan
"""

# Justificación: Al ser filas 100% idénticas, se consideran errores de carga o redundancia.
antes = len(df_limpio)
df_limpio = df_limpio.drop_duplicates(keep='first')
despues = len(df_limpio)

print(f"Filas eliminadas: {antes - despues}")
# Filas duplicadas
print(f"\nTotal de filas duplicadas: {df_limpio.duplicated().sum()}")

df_limpio.info()

"""**NOTA**: Ahora que se eliminan los duplicaoms podemos deducir que podriamos tener otros valores duplicadospor los nombres, ya que estos se encuentran en mezcla de mayusculas y minusculas, por lo que despues de limpiar los nombres debemos volver a validar los duplicados porq podria tener esto:

*   AmbEr es diferente de AMBEr, pero puede ser el mismo registro

##
"""

# Primero estandarizamos los nombres (ahora "AmbEr" y "AMBEr" serán "Amber")
df_limpio['name'] = df_limpio['name'].str.title()
df_limpio['doctor'] = df_limpio['doctor'].str.title()
df_limpio['hospital'] = df_limpio['hospital'].str.title() # También el hospital por si acaso

# Validamos que se haya limpiado correctamente la data
print(df_limpio['name'].unique())
print(df_limpio['doctor'].unique())
print(df_limpio['hospital'].unique())

"""Ahora volvermos a buscar los duplicados con la limpieza hecha para validar que en realidad son registros diferentes

---


"""

# 2. Ahora volvemos a buscar duplicados que antes estaban ocultos por el formato
antes_segunda_limpieza = len(df_limpio)
df_limpio = df_limpio.drop_duplicates(keep='first')
despues_segunda_limpieza = len(df_limpio)

duplicados_ocultos = antes_segunda_limpieza - despues_segunda_limpieza
print(f"Duplicados exactos eliminados antes: 534")
print(f"Duplicados 'ocultos' encontrados tras normalizar nombres: {duplicados_ocultos}")
print(f"Total de registros limpios: {len(df_limpio)}")

"""Podemos ver que no hay duplicados, por lo que mantenemos los 54966 registros como se tenia previsto

## Consistencia de Fechas

Ahora procesamos las fechas a tipo de dato datetime, para facilitarnos y realizar el calculo de los dias de estancia
"""

# Justificación: Convertir a datetime permite realizar cálculos matemáticos con el tiempo.
# Crear 'days_of_stay' transforma datos crudos en una métrica de negocio (KPI de hospitalización).

df_limpio['date_of_admission'] = pd.to_datetime(df_limpio['date_of_admission'])
df_limpio['discharge_date'] = pd.to_datetime(df_limpio['discharge_date'])

df_limpio['days_of_stay'] = (df_limpio['discharge_date'] - df_limpio['date_of_admission']).dt.days

# Verificación rápida:
print(f"Rango de estancia: {df_limpio['days_of_stay'].min()} a {df_limpio['days_of_stay'].max()} días.")

df_limpio.info()

"""## Tratamiento de negativos - Billing Amount

Decisión: Se ha transformado la columna billing_amount a valores absolutos, redondeados a dos decimales, y se ha creado una variable auxiliar denominada billing_nature.


* En lugar de representar los reembolsos o créditos con un signo negativo (-), se optó por una arquitectura de datos de "etiquetado categórico":

* Un signo negativo puede interpretarse erróneamente como un error de ingreso de datos. Al crear la columna billing_nature (con valores: Ingreso o Ajuste), la naturaleza de la transacción es explícita.

* Optimización de Consultas: Para un analista de negocio (o un tablero en Power BI/Tableau), es mucho más rápido filtrar por la categoría "Ajuste" que realizar filtros matemáticos complejos sobre valores menores a cero.

* Psicología del Usuario: En la presentación de informes, el uso de etiquetas descriptivas reduce la carga cognitiva del usuario y evita confusiones sobre si el hospital "perdió" dinero o simplemente realizó una devolución administrativa.
"""

import numpy as np

# Creamos la nueva columna de "Naturaleza de la Transacción"
# Si el monto es >= 0 es 'Ingreso', de lo contrario es 'Ajuste' (Reembolso)
df_limpio['billing_nature'] = np.where(df_limpio['billing_amount'] >= 0, 'Ingreso', 'Ajuste')

# 2. Transformamos el monto a positivo (Valor Absoluto)
df_limpio['billing_amount'] = df_limpio['billing_amount'].abs()

# 3. Redondeamos a 2 decimales (Estándar Contable)
df_limpio['billing_amount'] = df_limpio['billing_amount'].round(2)

# 4. Convertimos la nueva columna a 'category' para ahorrar memoria
df_limpio['billing_nature'] = df_limpio['billing_nature'].astype('category')

# Verificamos cómo quedó
print(df_limpio[['billing_amount', 'billing_nature']].head())

df_limpio['billing_nature'].unique().tolist()

"""## Validaciones

Por ultimo realizamos un análsis de los datos ya limpios y volvemos a validar nulos, blancos duplicados y ciertas inconsistencias que puedan aparecer
"""

df_limpio

#  Estadísticas Descriptivas (Numéricas y Categóricas)
print("\n[INFO] Estadísticas de Variables Numéricas:")
display(df_limpio.describe())

print("\n[INFO] Estadísticas de Variables Categóricas:")
display(df_limpio.describe(include=['category']))

import pandas as pd
import numpy as np


# Validación de Nulos y Blancos
nulls = df_limpio.isnull().sum().sum()

# Buscamos blancos solo en columnas que tengan texto
blancos = 0
for col in df_limpio.columns:
    if df_limpio[col].dtype.name in ['object', 'category']:
        blancos += (df_limpio[col].astype(str).str.strip() == "").sum()

# Validación de Duplicados
duplicados = df_limpio.duplicated().sum()

# 5. Validaciones de Lógica
errores_edad = len(df_limpio[df_limpio['age'] < 0])
errores_estancia = len(df_limpio[df_limpio['days_of_stay'] < 0])
errores_monto = len(df_limpio[df_limpio['billing_amount'] < 0])

# --- REPORTE FINAL ---
print(f" Nulos encontrados: {nulls}")
print(f"Valores en blanco: {blancos}")
print(f"Duplicados: {duplicados}")
print(f"Errores lógicos en Edad: {errores_edad}")
print(f"Errores lógicos en Estancia: {errores_estancia}")
print(f"Errores lógicos en Montos (Negativos): {errores_monto}")

if nulls == 0 and blancos == 0 and duplicados == 0 and errores_edad == 0 and errores_monto == 0:
    print("\n¡DATASET LIMPIO Y LISTO PARA EXPORTAR!")
else:
    print("Aún quedan detalles por corregir.")

"""Exportamos el dataset limpio"""

nombre_archivo = 'healthcare_dataset_clean.csv'
df_limpio.to_csv(nombre_archivo, index=False)