# -*- coding: utf-8 -*-
"""Prueba Técnica — Data Engineer Intern.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VKUBwPElwSPr4QK_9rUOPkjW1YL0jMi7

# Fase 1 - Exploración de datos
Lo primero que se realizará es la exploración de los datos con ayuda de Colab para el pr-análisis del estado de los datos
"""

import pandas as pd

df = pd.read_csv("/content/healthcare_dataset.csv")
df

"""Revisamos las caracteristicas de los valores asi como el total de registros     """

df.info()

"""## Valores  nulos, blancos

Lo primero que revisamos es:


*  **Valores Nulos**: aunque la funcion .info() nos menciona que no, podemos revisarlo por nuestra cuenta para una doble verificación
*  **Valores blancos**: revisar si los datos tienen valores completos pero que pueden ser "basura" ya que solo esta completado para no tener nulos
*   **Valores duplicados**: revisar si existen valores duplicados entre la combinacion de todas las variables
"""

# Conteo de valores nulos (NaN)
null_count = df.isnull().sum()

# Conteo de valores en blanco (strings vacíos o solo espacios)
blank_count = (df.astype(str).apply(lambda x: x.str.strip()) == "").sum()

# 3. Porcentaje de datos faltantes
missing_percent = (null_count / len(df)) * 100

df_diagnosis = pd.DataFrame({
    'Tipo de Dato': df.dtypes,
    'Nulos (NaN)': null_count,
    'Blancos (" ")': blank_count,
    '% Faltante Total': missing_percent
})

print("--- Diagnóstico de Calidad de Datos ---")
print(df_diagnosis)

# Filas duplicadas
print(f"\nTotal de filas duplicadas: {df.duplicated().sum()}")

"""## Valores duplicados

Observamos que no se tiene valores tanto nulos como ben blanco pero si se tiene valores duplicados por lo que revisaremos si esos valores son en realidad duplciados y de que tipo son
"""

# Filtramos el dataframe para mostrar SOLO las filas que tienen duplicados
df_repetidos = df[df.duplicated(keep=False)]

# Ordenamos por todas las columnas para que las filas idénticas aparezcan juntas
df_repetidos_ordenados = df_repetidos.sort_values(by=list(df.columns))

# Mostramos los primeros 10 registros de este grupo de duplicados
print("--- Visualización de registros duplicados (Filas idénticas juntas) ---")
if not df_repetidos_ordenados.empty:
    print(df_repetidos_ordenados.head(10))
else:
    print("No se encontraron filas duplicadas exactas en el dataset.")

"""Con esto nos damos cuenta de que son por tal cual por valores duplicadosen el registro, asi que lo que sigue ahora es saber si son solo valores que se insertaron 2 veces o mas, por lo que se ve cuanto es el conteo de duplicados por cada valor, teniendo el resumen para saber las veces que se repite"""

# Contamos cuántas veces aparece cada combinación de filas
frecuencia_duplicados = df.groupby(df.columns.tolist()).size().reset_index(name='cantidad')

# Filtramos para quedarnos solo con los que aparecen más de 1 vez
solo_duplicados = frecuencia_duplicados[frecuencia_duplicados['cantidad'] > 1]

# Ordenamos de mayor a menor para ver los "peores" casos primero
solo_duplicados = solo_duplicados.sort_values(by='cantidad', ascending=False)

print("--- Top 10 de registros más repetidos ---")
print(solo_duplicados.head(10))

# Resumen de las repeticiones
print("\n--- Distribución de las repeticiones ---")
print(solo_duplicados['cantidad'].value_counts().sort_index().rename_axis('Veces que se repite').reset_index(name='Cantidad de grupos'))

"""Al saber que solo se tiene 2 valores duplicadosen un total de 534, lo que se presencio al inicio, son filas duplicadas 2 veces por lo que se arregla eliminando la duplicada

Algo que resaltar en esta parte es que la varibale name tiene datos con letras mayusculas y minusculas mezcladas, por lo que en la limpieza de los datos se consideraria dejar solo la primera en mayuscula y las demas en minuscula.

## Valores unicos
"""

print("--- Valores únicos por columna ---")
print(df.nunique())

"""Revisamos los valores unicos en cada una de las columnas, para ver si hay datos sucios, ya que claro mencionamos que no hay nulos y blancos pero no necesariamente significa que sea valida esa data"""

print("--- Exploración de Valores Únicos (Orden Ascendente) ---\n")

for columna in df.columns:
    # Obtener valores únicos, quitar nulos y convertir a lista de Python pura
    unique_values = df[columna].unique().tolist()
    total_unicos = len(unique_values)

    # Ordenar de forma ascendente estándar
    valores_ordenados = sorted(unique_values)

    print(f"Columna: '{columna}' | Tipo: {df[columna].dtype} | Únicos: {total_unicos}")

    # Mostrar la muestra de los 20 primeros
    if total_unicos > 20:
        print(f"Muestra de los 20 primeros:")
        print(valores_ordenados[:20])
    else:
        print(f"Todos los valores:")
        print(valores_ordenados)

    print("-" * 50)

"""## Valores Atipicos

Revisamos los valores apiticos para cada columna, para lo que ellos nos resulta mas facil observar estos valore sen histogramas, para ver la dispersion de los datos

Primero transformamos los datos categoricos a valores numericos para que sea posible realizar las graficas
"""

# Identificar columnas categóricas (las que son tipo 'object')
categoricas = df.select_dtypes(include=['object']).columns

# Creamos un nuevo DataFrame para no arruinar el original
df_numerico = df.copy()

for col in categoricas:
    df_numerico[col] = df_numerico[col].astype('category').cat.codes

print(df_numerico.head())

import matplotlib.pyplot as plt

# Primero normalizamos nombres para evitar el KeyError
df_numerico.columns = df_numerico.columns.str.strip().str.lower().str.replace(' ', '_')

# Dibujamos histogramas de todas las columnas numéricas
df_numerico.hist(figsize=(15, 10), bins=30, edgecolor='black')
plt.suptitle('Distribución de Variables Numéricas (Campanas)', fontsize=16)
plt.tight_layout()
plt.show()

"""Observamos que no existen valores atipicos representativos o casi no estan presentes,

## Validaciones de fecha

Ahora validamos las fechas de admision con las de alta, asi para identificar si hay valores que no sean del tipo, lo admiti el dia jueves 10 y lo di de alta el dia martes 08, como ejemplo, por lo que una nueva variable "days_of_stay" vamos a crear
"""

# Aseguramos que las columnas sean tipo fecha (datetime)
df['date_of_admission'] = pd.to_datetime(df['date_of_admission'])
df['discharge_date'] = pd.to_datetime(df['discharge_date'])

# Calculamos la diferencia y extraemos solo el número de días
df['days_of_stay'] = (df['discharge_date'] - df['date_of_admission']).dt.days

# Revisamos los primeros resultados
print(df[['date_of_admission', 'discharge_date', 'days_of_stay']].head())

df.describe()

print(sorted(df["days_of_stay"].unique().tolist()))